const fakeData: Array<Object> = [
  {
    userId : 2,
    domain : 'app.brandmark.io',
    url : 'app.brandmark.io/v2/',
    fullUrl : 'https://app.brandmark.io/v2/',
    fullTitle : 'Brandmark - make your logo in minutes',
    text : 'Use the open-source EXE firewall, then you can transmit the optical hard drive!',
    createdAt : '2020-01-25T10:48:39.344Z',
    timeSpent : 30328,
  },
  {
    userId : 4,
    domain : 'trello.com',
    url : 'trello.com/b/8GsNaHVX/thesis-project-codeworks',
    fullUrl : 'https://trello.com/b/8GsNaHVX/thesis-project-codeworks',
    fullTitle : 'Thesis Project Codeworks | Trello',
    text : 'If we input the protocol, we can get to the SMTP microchip through the open-source EXE firewall!',
    createdAt : '2020-01-25T10:47:35.091Z',
    timeSpent : 19622,
  },
  {
    userId : 3,
    domain : 'www.notion.so',
    url : 'www.notion.so/Organization-617c2e32853e43eb894b79142e88959d',
    fullUrl : 'https://www.notion.so/Organization-617c2e32853e43eb894b79142e88959d',
    fullTitle : 'Organization',
    text : "You can't reboot the capacitor without compressing the wireless IB pixel!",
    createdAt : '2020-01-25T10:44:26.629Z',
    timeSpent : 444,
  },
  {
    userId : 2,
    domain : 'trello.com',
    url : 'trello.com/c/TmBrUOOa/11-find-a-logo',
    fullUrl : 'https://trello.com/c/TmBrUOOa/11-find-a-logo',
    fullTitle : 'Thesis Project Codeworks | Trello',
    text : "parsing the program won't do anything, we need to index the virtual FTP interface!",
    createdAt : '2020-01-25T10:34:27.637Z',
    timeSpent : 35312,
  },
  {
    userId : 3,
    domain : 'trello.com',
    url : 'trello.com/c/lg3X2Jrv/10-do-a-backend-with-a-get-and-a-post',
    fullUrl : 'https://trello.com/c/lg3X2Jrv/10-do-a-backend-with-a-get-and-a-post',
    fullTitle : 'find a logo de Thesis Project Codeworks | Trello',
    text : 'The AI sensor is down, calculate the digital panel so we can input the PNG capacitor!',
    createdAt : '2020-01-25T10:32:05.070Z',
    timeSpent : 25934,
  },
  {
    userId : 1,
    domain : 'brandmark.io',
    url : 'brandmark.io/',
    fullUrl : 'https://brandmark.io/',
    fullTitle : 'Brandmark Logo Maker - the most advanced AI logo design tool',
    text : "You can't generate the circuit without connecting the solid state XSS pixel!",
    createdAt : '2020-01-25T10:22:58.352Z',
    timeSpent : 34950,
  },
  {
    userId : 2,
    domain : 'brandmark.io',
    url : 'brandmark.io/tools/',
    fullUrl : 'https://brandmark.io/tools/',
    fullTitle : 'Brandmark - tools',
    text : 'If we hack the protocol, we can get to the AI bandwidth through the digital COM feed!',
    createdAt : '2020-01-25T10:22:55.178Z',
    timeSpent : 16440,
  },
  {
    userId : 2,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=logo+maker+ai&oq=logo+maker+ai&aqs=chrome..69i57j0l7.2407j1j1&sourceid=chrome&ie=UTF-8',
    fullTitle : 'logo maker ai - Google Search',
    text : 'Use the primary XML interface, then you can copy the redundant firewall!',
    createdAt : '2020-01-25T10:22:45.095Z',
    timeSpent : 35592,
  },
  {
    userId : 4,
    domain : 'abkfbakhjpmblaafnpgjppbmioombali',
    url : 'abkfbakhjpmblaafnpgjppbmioombali/options.html',
    fullUrl : 'chrome-extension://abkfbakhjpmblaafnpgjppbmioombali/options.html#/overview',
    fullTitle : '🔍 Results',
    text : 'Try to parse the SCSI array, maybe it will index the solid state pixel!',
    createdAt : '2020-01-25T08:59:40.740Z',
    timeSpent : 28507,
  },
  {
    userId : 3,
    domain : 'abkfbakhjpmblaafnpgjppbmioombali',
    url : 'abkfbakhjpmblaafnpgjppbmioombali/options.html',
    fullUrl : 'chrome-extension://abkfbakhjpmblaafnpgjppbmioombali/options.html#/overview?query=tes',
    fullTitle : '🔍 Results',
    text : 'If we transmit the application, we can get to the XSS sensor through the haptic SAS firewall!',
    createdAt : '2020-01-25T08:57:45.606Z',
    timeSpent : 24284,
  },
  {
    userId : 4,
    domain : 'developer.chrome.com',
    url : 'developer.chrome.com/extensions/runtime',
    fullUrl : 'https://developer.chrome.com/extensions/runtime#property-lastError',
    fullTitle : 'chrome.runtime - Google Chrome',
    text : 'Use the wireless XML microchip, then you can parse the auxiliary feed!',
    createdAt : '2020-01-25T08:34:58.027Z',
    timeSpent : 23736,
  },
  {
    userId : 3,
    domain : 'developer.chrome.com',
    url : 'developer.chrome.com/extensions/storage',
    fullUrl : 'https://developer.chrome.com/extensions/storage#property-sync',
    fullTitle : 'chrome.storage - Google Chrome',
    text : 'Use the neural CSS bus, then you can connect the primary application!',
    createdAt : '2020-01-25T08:34:50.865Z',
    timeSpent : 15397,
  },
  {
    userId : 2,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=chrome+storage+client&oq=chrome+storage+client&aqs=chrome..69i57j33.5079j1j4&sourceid=chrome&ie=UTF-8',
    fullTitle : 'chrome storage client - Google Search',
    text : 'If we input the interface, we can get to the JBOD panel through the haptic SQL panel!',
    createdAt : '2020-01-25T00:36:58.167Z',
    timeSpent : 32065,
  },
  {
    userId : 3,
    domain : 'developer.chrome.com',
    url : 'developer.chrome.com/apps/storage',
    fullUrl : 'https://developer.chrome.com/apps/storage',
    fullTitle : 'chrome.storage - Google Chrome',
    text : 'If we bypass the application, we can get to the IB feed through the open-source SAS driver!',
    createdAt : '2020-01-25T00:36:14.394Z',
    timeSpent : 27870,
  },
  {
    userId : 3,
    domain : 'developer.chrome.com',
    url : 'developer.chrome.com/extensions/manifest/incognito',
    fullUrl : 'https://developer.chrome.com/extensions/manifest/incognito',
    fullTitle : 'Manifest - Incognito - Google Chrome',
    text : 'We need to hack the mobile SSL array!',
    createdAt : '2020-01-25T00:26:10.401Z',
    timeSpent : 13263,
  },
  {
    userId : 4,
    domain : 'developer.chrome.com',
    url : 'developer.chrome.com/extensions/storage',
    fullUrl : 'https://developer.chrome.com/extensions/storage',
    fullTitle : 'chrome.storage - Google Chrome',
    text : "I'll connect the back-end AI pixel, that should card the SAS matrix!",
    createdAt : '2020-01-25T00:25:31.327Z',
    timeSpent : 1508,
  },
  {
    userId : 1,
    domain : 'stackoverflow.com',
    url : 'stackoverflow.com/questions/24171306/how-can-i-sync-to-extension-local-storage-in-content-script',
    fullUrl : 'https://stackoverflow.com/questions/24171306/how-can-i-sync-to-extension-local-storage-in-content-script',
    fullTitle : 'javascript - How can I sync to extension local storage in content script? - Stack Overflow',
    text : 'The COM application is down, back up the primary program so we can calculate the PNG sensor!',
    createdAt : '2020-01-25T00:24:11.877Z',
    timeSpent : 23185,
  },
  {
    userId : 2,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?sxsrf=ACYBGNQ8ybneNCkcCxnYf5CeUm0dv_rd8A%3A1579911808042&ei=gIorXs2jAsXggwfe44TQDw&q=chrome+extension+storage+between+background+and+content+script&oq=chrome+extension+storage+between&gs_l=psy-ab.3.0.33i22i29i30l9.27582.36427..37731...8.1..0.137.2032.14j8......0....1..gws-wiz.......0i71j35i39j0j0i131j0i20i263j0i10j0i13.2gq2f4iyNkk',
    fullTitle : 'chrome extension storage between background and content script - Google Search',
    text : 'Use the solid state XSS firewall, then you can override the redundant application!',
    createdAt : '2020-01-25T00:24:07.708Z',
    timeSpent : 38558,
  },
  {
    userId : 1,
    domain : 'itnext.io',
    url : 'itnext.io/all-youll-ever-need-to-know-about-chrome-extensions-ceede9c28836',
    fullUrl : 'https://itnext.io/all-youll-ever-need-to-know-about-chrome-extensions-ceede9c28836',
    fullTitle : 'All you’ll ever need to know about Chrome Extensions',
    text : "You can't copy the sensor without transmitting the virtual SDD driver!",
    createdAt : '2020-01-25T00:23:46.155Z',
    timeSpent : 38844,
  },
  {
    userId : 3,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=chrome+extension+communication+between+background+and+content+script&oq=chrome+storage+between+backgrou&aqs=chrome.1.69i57j0.12535j1j1&sourceid=chrome&ie=UTF-8',
    fullTitle : 'chrome extension communication between background and content script - Google Search',
    text : 'If we copy the driver, we can get to the USB panel through the primary SQL hard drive!',
    createdAt : '2020-01-25T00:23:29.124Z',
    timeSpent : 19360,
  },
  {
    userId : 2,
    domain : 'developer.chrome.com',
    url : 'developer.chrome.com/extensions/tabs',
    fullUrl : 'https://developer.chrome.com/extensions/tabs#type-MutedInfo',
    fullTitle : 'chrome.tabs - Google Chrome',
    text : 'Use the redundant JSON alarm, then you can index the solid state driver!',
    createdAt : '2020-01-25T00:20:52.377Z',
    timeSpent : 18448,
  },
  {
    userId : 3,
    domain : 'developer.chrome.com',
    url : 'developer.chrome.com/extensions/tabs',
    fullUrl : 'https://developer.chrome.com/extensions/tabs#event-onActiveChanged',
    fullTitle : 'chrome.tabs - Google Chrome',
    text : 'The ADP alarm is down, bypass the back-end program so we can compress the SMS program!',
    createdAt : '2020-01-25T00:20:50.340Z',
    timeSpent : 39986,
  },
  {
    userId : 3,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=chrome+extension+local+storage&oq=chrome+extension+loca&aqs=chrome.2.0j69i57j0l6.7335j1j4&sourceid=chrome&ie=UTF-8',
    fullTitle : 'chrome extension local storage - Google Search',
    text : 'If we index the pixel, we can get to the SMTP microchip through the back-end USB port!',
    createdAt : '2020-01-25T00:18:06.207Z',
    timeSpent : 19292,
  },
  {
    userId : 2,
    domain : 'en.wikipedia.org',
    url : 'en.wikipedia.org/wiki/Main_Page',
    fullUrl : 'https://en.wikipedia.org/wiki/Main_Page',
    fullTitle : 'Wikipedia, the free encyclopedia',
    text : 'Try to transmit the PCI bandwidth, maybe it will hack the open-source firewall!',
    createdAt : '2020-01-25T00:17:44.385Z',
    timeSpent : 8501,
  },
  {
    userId : 2,
    domain : 'en.wikipedia.org',
    url : 'en.wikipedia.org/w/index.php',
    fullUrl : 'https://en.wikipedia.org/w/index.php?title=Software_testing&action=edit',
    fullTitle : 'Editing Software testing - Wikipedia',
    text : 'We need to program the virtual SCSI pixel!',
    createdAt : '2020-01-25T00:17:33.855Z',
    timeSpent : 816,
  },
  {
    userId : 1,
    domain : 'en.wikipedia.org',
    url : 'en.wikipedia.org/wiki/Software_testing',
    fullUrl : 'https://en.wikipedia.org/wiki/Software_testing',
    fullTitle : 'Software testing - Wikipedia',
    text : "hacking the interface won't do anything, we need to compress the mobile RAM card!",
    createdAt : '2020-01-25T00:16:58.013Z',
    timeSpent : 20421,
  },
  {
    userId : 3,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=testing&oq=test&aqs=chrome.0.69i59l2j69i57j0l2j69i61j69i60j69i61.848j1j1&sourceid=chrome&ie=UTF-8',
    fullTitle : 'testing - Google Search',
    text : "navigating the firewall won't do anything, we need to connect the bluetooth IB program!",
    createdAt : '2020-01-25T00:15:53.377Z',
    timeSpent : 35323,
  },
  {
    userId : 1,
    domain : 'www.textnow.com',
    url : 'www.textnow.com/',
    fullUrl : 'https://www.textnow.com/',
    fullTitle : 'Free Texting & Calling App | Free Phone Service | TextNow',
    text : 'We need to override the 1080p THX bandwidth!',
    createdAt : '2020-01-25T00:14:54.621Z',
    timeSpent : 25806,
  },
  {
    userId : 4,
    domain : 'www.textnow.com',
    url : 'www.textnow.com/login',
    fullUrl : 'https://www.textnow.com/login',
    fullTitle : 'TextNow',
    text : 'The SCSI bus is down, hack the online microchip so we can quantify the SSL card!',
    createdAt : '2020-01-25T00:13:16.030Z',
    timeSpent : 21234,
  },
  {
    userId : 1,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=text&oq=text&aqs=chrome..69i57j69i59j0l3j69i60l3.1167j1j1&sourceid=chrome&ie=UTF-8',
    fullTitle : 'text - Google Search',
    text : "I'll transmit the virtual THX feed, that should firewall the CSS card!",
    createdAt : '2020-01-25T00:13:11.151Z',
    timeSpent : 24892,
  },
  {
    userId : 2,
    domain : 'developer.mozilla.org',
    url : 'developer.mozilla.org/en-US/docs/Web/API/Window/localStorage',
    fullUrl : 'https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage',
    fullTitle : 'Window.localStorage - Web APIs | MDN',
    text : "I'll calculate the cross-platform USB panel, that should hard drive the PCI card!",
    createdAt : '2020-01-25T00:06:27.818Z',
    timeSpent : 19210,
  },
  {
    userId : 2,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=js+localstorage&oq=js+localstorage&aqs=chrome..69i57j0l7.2846j1j1&sourceid=chrome&ie=UTF-8',
    fullTitle : 'js localstorage - Google Search',
    text : 'The SQL microchip is down, calculate the optical feed so we can back up the AI capacitor!',
    createdAt : '2020-01-25T00:06:25.220Z',
    timeSpent : 97,
  },
  {
    userId : 2,
    domain : 'developer.chrome.com',
    url : 'developer.chrome.com/extensions/tabs',
    fullUrl : 'https://developer.chrome.com/extensions/tabs#event-onUpdated',
    fullTitle : 'chrome.tabs - Google Chrome',
    text : "You can't override the monitor without bypassing the 1080p FTP program!",
    createdAt : '2020-01-24T23:58:03.374Z',
    timeSpent : 12373,
  },
  {
    userId : 4,
    domain : 'eslint.org',
    url : 'eslint.org/docs/rules/no-use-before-define',
    fullUrl : 'https://eslint.org/docs/rules/no-use-before-define',
    fullTitle : 'no-use-before-define - Rules - ESLint - Pluggable JavaScript linter',
    text : 'The TCP bus is down, navigate the virtual bus so we can compress the GB driver!',
    createdAt : '2020-01-24T23:52:34.911Z',
    timeSpent : 4686,
  },
  {
    userId : 3,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=eslint+no+use+before+define&oq=eslintrc+no+use&aqs=chrome.1.69i57j0l7.5505j1j9&sourceid=chrome&ie=UTF-8',
    fullTitle : 'eslint no use before define - Google Search',
    text : 'Try to bypass the SMS capacitor, maybe it will compress the bluetooth interface!',
    createdAt : '2020-01-24T23:52:30.646Z',
    timeSpent : 23669,
  },
  {
    userId : 2,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=je+sais+pas&sxsrf=ACYBGNRFDKMNK-a4CtdhmVbaI8eSYv_tVA:1579909095919&source=lnms&sa=X&ved=0ahUKEwiQ7cGDtJ3nAhWt4IUKHag1B3IQ_AUICSgA&biw=1109&bih=1066&dpr=2',
    fullTitle : 'je sais pas - Google Search',
    text : 'The HDD alarm is down, navigate the mobile feed so we can input the SMS card!',
    createdAt : '2020-01-24T23:38:19.718Z',
    timeSpent : 14166,
  },
  {
    userId : 2,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=je+sais+pas&tbm=nws&sxsrf=ACYBGNRxN2M6gGdWzB_Q7_y4KCGIVwTuNg:1579909068185&source=lnms&sa=X&ved=0ahUKEwjviaX2s53nAhXGPsAKHQSXBQUQ_AUIESgE&biw=1109&bih=1066&dpr=2',
    fullTitle : 'je sais pas - Google Search',
    text : 'If we connect the bus, we can get to the RSS bandwidth through the multi-byte XSS capacitor!',
    createdAt : '2020-01-24T23:38:16.539Z',
    timeSpent : 27210,
  },
  {
    userId : 2,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=je+sais+pas&sxsrf=ACYBGNR5ANiYHJXSoqNv-f8W5-JBfzFNcA:1579909056365&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjh1dPws53nAhWOxYUKHfkCCgIQ_AUoAXoECA8QAw&cshid=1579909066230921&biw=1109&bih=1066',
    fullTitle : 'je sais pas - Google Search',
    text : 'If we transmit the microchip, we can get to the SDD bandwidth through the redundant SDD sensor!',
    createdAt : '2020-01-24T23:37:48.688Z',
    timeSpent : 17263,
  },
  {
    userId : 1,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=je+sais+pas&sxsrf=ACYBGNSTVdlGq0GhSBTp6i6ZstqwJrgAow:1579909059719&source=lnms&sa=X&ved=0ahUKEwjMqaDys53nAhUIXMAKHQvBDUcQ_AUIDSgA&biw=1109&bih=1066&dpr=2',
    fullTitle : 'je sais pas - Google Search',
    text : 'Use the digital COM firewall, then you can generate the redundant bus!',
    createdAt : '2020-01-24T23:37:46.580Z',
    timeSpent : 12247,
  },
  {
    userId : 2,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=je+sais+pas&sxsrf=ACYBGNR5ANiYHJXSoqNv-f8W5-JBfzFNcA:1579909056365&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjh1dPws53nAhWOxYUKHfkCCgIQ_AUoAXoECA8QAw&biw=1109&bih=1066',
    fullTitle : 'je sais pas - Google Search',
    text : "I'll connect the neural SCSI protocol, that should transmitter the ADP firewall!",
    createdAt : '2020-01-24T23:37:40.559Z',
    timeSpent : 20882,
  },
  {
    userId : 1,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=je+sais+pas&oq=je+sais+pas&aqs=chrome.0.0l8.1886j1j1&sourceid=chrome&ie=UTF-8',
    fullTitle : 'je sais pas - Google Search',
    text : "You can't transmit the firewall without bypassing the 1080p CSS monitor!",
    createdAt : '2020-01-24T23:37:37.109Z',
    timeSpent : 30921,
  },
  {
    userId : 3,
    domain : 'developer.chrome.com',
    url : 'developer.chrome.com/extensions/tabs',
    fullUrl : 'https://developer.chrome.com/extensions/tabs',
    fullTitle : 'chrome.tabs - Google Chrome',
    text : 'The AI capacitor is down, calculate the redundant driver so we can override the SDD program!',
    createdAt : '2020-01-24T23:21:54.850Z',
    timeSpent : 30448,
  },
  {
    userId : 4,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?sxsrf=ACYBGNThc6qaEl2ulfzAKaBdSoB0xavqNg%3A1579908067577&ei=43srXuTmIsOJjLsP5rq9oAo&q=chrome.tab+before+remove&oq=chrome.tab+before+remove&gs_l=psy-ab.3..33i22i29i30l10.12476.17787..18429...0.5..1.240.982.5j3j1......0....1..gws-wiz.......0i71j0i22i30.yQrBRRCDkEw&ved=0ahUKEwik5JSZsJ3nAhXDBGMBHWZdD6QQ4dUDCAs&uact=5',
    fullTitle : 'chrome.tab before remove - Google Search',
    text : 'The SQL bus is down, back up the auxiliary transmitter so we can reboot the SDD system!',
    createdAt : '2020-01-24T23:21:49.772Z',
    timeSpent : 23853,
  },
  {
    userId : 3,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?sxsrf=ACYBGNRaaARn51AkMCcbM9_OyVaRRp-jnA%3A1579908043389&ei=y3srXt-oF_XYgwfaroboAQ&q=chrome+plugin+tab+before+closing+tabs&oq=chrome+plugin+tab+before&gs_l=psy-ab.3.0.33i160l2.14963.20761..23416...3.1..0.140.2256.24j3......0....1..gws-wiz.......0i71j35i39j0i273j0i67j0i131j0j0i10j35i305i39j0i20i263j0i8i67j0i22i30j0i333j33i22i29i30.X08jE0-5Cc4',
    fullTitle : 'chrome plugin tab before closing tabs - Google Search',
    text : "parsing the firewall won't do anything, we need to synthesize the back-end AGP port!",
    createdAt : '2020-01-24T23:21:29.663Z',
    timeSpent : 12428,
  },
  {
    userId : 3,
    domain : 'support.google.com',
    url : 'support.google.com/chrome/thread/1870333',
    fullUrl : 'https://support.google.com/chrome/thread/1870333?hl=en',
    fullTitle : 'Can i make Chrome ask before closing all tabs? - Google Chrome Help',
    text : "You can't parse the protocol without overriding the virtual SDD application!",
    createdAt : '2020-01-24T23:21:12.312Z',
    timeSpent : 15180,
  },
  {
    userId : 1,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=save+chrome+tabs+before+closing&oq=chrome+tab+befor&aqs=chrome.1.69i57j0l2.9095j1j1&sourceid=chrome&ie=UTF-8',
    fullTitle : 'save chrome tabs before closing - Google Search',
    text : 'The THX transmitter is down, compress the online port so we can parse the GB protocol!',
    createdAt : '2020-01-24T23:20:44.061Z',
    timeSpent : 3064,
  },
  {
    userId : 3,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=hello&oq=hello&aqs=chrome.0.69i59l2j0l3j69i60l3.895j1j1&sourceid=chrome&ie=UTF-8',
    fullTitle : 'hello - Google Search',
    text : 'The AGP bus is down, input the auxiliary application so we can calculate the ADP matrix!',
    createdAt : '2020-01-24T22:47:54.871Z',
    timeSpent : 29149,
  },
  {
    userId : 3,
    domain : 'makitweb.com',
    url : 'makitweb.com/how-to-detect-browser-window-active-or-not-javascript/',
    fullUrl : 'https://makitweb.com/how-to-detect-browser-window-active-or-not-javascript/',
    fullTitle : 'How to Detect Browser Window is Active or not - JavaScript',
    text : 'The SDD bus is down, index the multi-byte driver so we can compress the SAS sensor!',
    createdAt : '2020-01-24T22:45:09.280Z',
    timeSpent : 22136,
  },
  {
    userId : 2,
    domain : 'en.wikipedia.org',
    url : 'en.wikipedia.org/wiki/59th_Annual_Grammy_Awards',
    fullUrl : 'https://en.wikipedia.org/wiki/59th_Annual_Grammy_Awards',
    fullTitle : '59th Annual Grammy Awards - Wikipedia',
    text : 'We need to navigate the digital JSON microchip!',
    createdAt : '2020-01-24T22:44:50.920Z',
    timeSpent : 9648,
  },
  {
    userId : 4,
    domain : 'chrome.google.com',
    url : 'chrome.google.com/webstore/detail/blur-it-out/aiocpnokjcmpelmlmekbjjblcompckhe',
    fullUrl : 'https://chrome.google.com/webstore/detail/blur-it-out/aiocpnokjcmpelmlmekbjjblcompckhe?hl=en',
    fullTitle : 'Blur It Out - Chrome Web Store',
    text : 'We need to index the optical HDD array!',
    createdAt : '2020-01-24T22:39:48.977Z',
    timeSpent : 972,
  },
  {
    userId : 1,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?sxsrf=ACYBGNRltTIFUfahz8_6RKr1Rvl-nJjOhw%3A1579899911978&ei=B1wrXrmqO9rTgwfvpoqABA&q=chrome+tabs+blur&oq=chrome+tabs+blur&gs_l=psy-ab.3..0j0i22i30.2658185.2662944..2664123...0.1..0.150.1707.10j7......0....1..gws-wiz.......0i71j35i39j0i273j0i131j0i20i263j0i67j0i10.P7-Pp0Ko-2M&ved=0ahUKEwj5yaLokZ3nAhXa6eAKHW-TAkAQ4dUDCAs&uact=5',
    fullTitle : 'chrome tabs blur - Google Search',
    text : 'We need to parse the neural SMTP capacitor!',
    createdAt : '2020-01-24T22:39:45.631Z',
    timeSpent : 18604,
  },
  {
    userId : 2,
    domain : 'developer.mozilla.org',
    url : 'developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch',
    fullUrl : 'https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch',
    fullTitle : 'Using Fetch - Web APIs | MDN',
    text : "You can't calculate the bandwidth without backing up the bluetooth HTTP pixel!",
    createdAt : '2020-01-24T22:37:34.720Z',
    timeSpent : 2706,
  },
  {
    userId : 3,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=js+fetch&oq=js+fetch&aqs=chrome..69i57j69i59j0l6.2519j1j1&sourceid=chrome&ie=UTF-8',
    fullTitle : 'js fetch - Google Search',
    text : "backing up the feed won't do anything, we need to connect the multi-byte SCSI card!",
    createdAt : '2020-01-24T22:37:33.632Z',
    timeSpent : 23250,
  },
  {
    userId : 1,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=js+detect+tab+blur&oq=js+detect+tab+blur&aqs=chrome..69i57j69i64.7775j1j4&sourceid=chrome&ie=UTF-8',
    fullTitle : 'js detect tab blur - Google Search',
    text : 'Use the bluetooth XSS hard drive, then you can connect the multi-byte matrix!',
    createdAt : '2020-01-24T21:45:55.589Z',
    timeSpent : 5958,
  },
  {
    userId : 1,
    domain : 'developer.mozilla.org',
    url : 'developer.mozilla.org/en-US/docs/Web/API/Window/blur_event',
    fullUrl : 'https://developer.mozilla.org/en-US/docs/Web/API/Window/blur_event',
    fullTitle : 'Window: blur event - Web APIs | MDN',
    text : 'If we hack the bandwidth, we can get to the HDD panel through the optical SQL array!',
    createdAt : '2020-01-24T21:44:03.707Z',
    timeSpent : 20741,
  },
  {
    userId : 4,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=window+on+blur&oq=window+on+blur&aqs=chrome..69i57j0l7.8304j1j4&sourceid=chrome&ie=UTF-8',
    fullTitle : 'window on blur - Google Search',
    text : 'The IB program is down, input the multi-byte feed so we can program the SAS circuit!',
    createdAt : '2020-01-24T21:43:58.276Z',
    timeSpent : 37220,
  },
  {
    userId : 2,
    domain : 'www.colors.commutercreative.com',
    url : 'www.colors.commutercreative.com/grid/',
    fullUrl : 'http://www.colors.commutercreative.com/grid/',
    fullTitle : '147 Colors | CSS Color Names',
    text : "compressing the card won't do anything, we need to back up the online THX hard drive!",
    createdAt : '2020-01-24T21:43:48.908Z',
    timeSpent : 17473,
  },
  {
    userId : 4,
    domain : 'support.google.com',
    url : 'support.google.com/chrome/thread/12666098',
    fullUrl : 'https://support.google.com/chrome/thread/12666098?hl=en',
    fullTitle : 'Filter: blur is bugged - Google Chrome Help',
    text : 'Use the neural USB program, then you can bypass the auxiliary microchip!',
    createdAt : '2020-01-24T21:43:29.746Z',
    timeSpent : 695,
  },
  {
    userId : 1,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=chrome+tabs+on+blur&oq=chrome+tabs+on+blur&aqs=chrome..69i57j0.5312j1j9&sourceid=chrome&ie=UTF-8',
    fullTitle : 'chrome tabs on blur - Google Search',
    text : 'We need to quantify the redundant JSON application!',
    createdAt : '2020-01-24T21:42:11.476Z',
    timeSpent : 28359,
  },
  {
    userId : 1,
    domain : 'stackoverflow.com',
    url : 'stackoverflow.com/questions/2720658/how-to-detect-when-a-tab-is-focused-or-not-in-chrome-with-javascript',
    fullUrl : 'https://stackoverflow.com/questions/2720658/how-to-detect-when-a-tab-is-focused-or-not-in-chrome-with-javascript',
    fullTitle : 'How to detect when a tab is focused or not in Chrome with Javascript? - Stack Overflow',
    text : 'We need to parse the cross-platform FTP pixel!',
    createdAt : '2020-01-24T21:41:33.051Z',
    timeSpent : 4002,
  },
  {
    userId : 1,
    domain : 'en.wikipedia.org',
    url : 'en.wikipedia.org/wiki/Adele',
    fullUrl : 'https://en.wikipedia.org/wiki/Adele',
    fullTitle : 'Adele - Wikipedia',
    text : 'The FTP sensor is down, navigate the auxiliary driver so we can synthesize the IB capacitor!',
    createdAt : '2020-01-24T21:39:29.430Z',
    timeSpent : 20277,
  },
  {
    userId : 1,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=hello&oq=hello&aqs=chrome.0.69i59l2j0l3j69i60l3.991j1j1&sourceid=chrome&ie=UTF-8',
    fullTitle : 'hello - Google Search',
    text : "I'll input the multi-byte JBOD protocol, that should feed the SAS microchip!",
    createdAt : '2020-01-24T21:38:02.169Z',
    timeSpent : 25353,
  },
  {
    userId : 4,
    domain : 'en.wikipedia.org',
    url : 'en.wikipedia.org/wiki/Hello_(Adele_song)',
    fullUrl : 'https://en.wikipedia.org/wiki/Hello_(Adele_song)',
    fullTitle : 'Hello (Adele song) - Wikipedia',
    text : "programming the monitor won't do anything, we need to synthesize the redundant HDD card!",
    createdAt : '2020-01-24T21:37:29.112Z',
    timeSpent : 26193,
  },
  {
    userId : 1,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=hello&oq=hello&aqs=chrome.0.69i59l2j0l3j69i60l3.1520j1j1&sourceid=chrome&ie=UTF-8',
    fullTitle : 'hello - Google Search',
    text : 'We need to hack the solid state GB firewall!',
    createdAt : '2020-01-24T21:36:57.674Z',
    timeSpent : 14335,
  },
  {
    userId : 4,
    domain : 'stackoverflow.com',
    url : 'stackoverflow.com/questions/221294/how-do-you-get-a-timestamp-in-javascript',
    fullUrl : 'https://stackoverflow.com/questions/221294/how-do-you-get-a-timestamp-in-javascript',
    fullTitle : 'date - How do you get a timestamp in JavaScript? - Stack Overflow',
    text : 'The PNG array is down, transmit the wireless system so we can bypass the THX card!',
    createdAt : '2020-01-24T21:36:34.075Z',
    timeSpent : 10171,
  },
  {
    userId : 4,
    domain : 'developer.chrome.com',
    url : 'developer.chrome.com/extensions/tabs',
    fullUrl : 'https://developer.chrome.com/extensions/tabs#method-sendMessage',
    fullTitle : 'chrome.tabs - Google Chrome',
    text : "I'll bypass the 1080p SAS hard drive, that should application the SMS bus!",
    createdAt : '2020-01-24T21:31:57.707Z',
    timeSpent : 4252,
  },
  {
    userId : 3,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=js+get+current+timestamp&oq=js+get+current+time&aqs=chrome.1.69i57j0l7.19535j1j1&sourceid=chrome&ie=UTF-8',
    fullTitle : 'js get current timestamp - Google Search',
    text : 'If we connect the microchip, we can get to the THX microchip through the multi-byte THX matrix!',
    createdAt : '2020-01-24T21:21:09.355Z',
    timeSpent : 7858,
  },
  {
    userId : 3,
    domain : 'www.toptal.com',
    url : 'www.toptal.com/software/definitive-guide-to-datetime-manipulation',
    fullUrl : 'https://www.toptal.com/software/definitive-guide-to-datetime-manipulation',
    fullTitle : 'Demystifying DateTime Manipulation in JavaScript | Toptal',
    text : 'Use the auxiliary GB matrix, then you can copy the back-end sensor!',
    createdAt : '2020-01-24T21:21:01.696Z',
    timeSpent : 11413,
  },
  {
    userId : 1,
    domain : 'developer.chrome.com',
    url : 'developer.chrome.com/extensions/tabs',
    fullUrl : 'https://developer.chrome.com/extensions/tabs#event-onActivated',
    fullTitle : 'chrome.tabs - Google Chrome',
    text : "compressing the feed won't do anything, we need to copy the solid state COM panel!",
    createdAt : '2020-01-24T21:14:55.864Z',
    timeSpent : 34143,
  },
  {
    userId : 2,
    domain : 'www.urbandictionary.com',
    url : 'www.urbandictionary.com/define.php',
    fullUrl : 'https://www.urbandictionary.com/define.php?term=Araz',
    fullTitle : 'Urban Dictionary: Araz',
    text : "connecting the firewall won't do anything, we need to connect the neural COM bus!",
    createdAt : '2020-01-24T21:14:28.795Z',
    timeSpent : 10749,
  },
  {
    userId : 1,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=araz&oq=araz&aqs=chrome..69i57j0l7.583j1j1&sourceid=chrome&ie=UTF-8',
    fullTitle : 'araz - Google Search',
    text : "I'll calculate the online JBOD matrix, that should application the USB system!",
    createdAt : '2020-01-24T21:14:25.939Z',
    timeSpent : 15212,
  },
  {
    userId : 2,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=chrome+tabs+on+close&oq=chrome+tabs+on+close&aqs=chrome..69i57j0l7.3887j1j9&sourceid=chrome&ie=UTF-8',
    fullTitle : 'chrome tabs on close - Google Search',
    text : 'Try to reboot the PCI bus, maybe it will program the solid state program!',
    createdAt : '2020-01-24T21:10:53.703Z',
    timeSpent : 35134,
  },
  {
    userId : 1,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=gdf&oq=gdf&aqs=chrome..69i57j0l7.470j1j1&sourceid=chrome&ie=UTF-8',
    fullTitle : 'gdf - Google Search',
    text : 'We need to index the cross-platform RSS microchip!',
    createdAt : '2020-01-24T21:10:42.608Z',
    timeSpent : 23489,
  },
  {
    userId : 2,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=testing&oq=test&aqs=chrome.0.69i59l2j69i57j0l5.999j1j1&sourceid=chrome&ie=UTF-8',
    fullTitle : 'testing - Google Search',
    text : 'Try to hack the SQL circuit, maybe it will compress the online application!',
    createdAt : '2020-01-24T21:05:12.078Z',
    timeSpent : 3160,
  },
  {
    userId : 2,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=chrome.tabs.onActivated&oq=chrome.tabs.onActivated+&aqs=chrome..69i57j69i59j0l5.7568j1j4&sourceid=chrome&ie=UTF-8',
    fullTitle : 'chrome.tabs.onActivated - Google Search',
    text : 'The USB protocol is down, reboot the cross-platform transmitter so we can reboot the TCP port!',
    createdAt : '2020-01-24T20:59:09.442Z',
    timeSpent : 25148,
  },
  {
    userId : 2,
    domain : 'stackoverflow.com',
    url : 'stackoverflow.com/questions/52443956/chrome-extension-recieve-message-in-the-tab-chrome-tabs-sendmessage',
    fullUrl : 'https://stackoverflow.com/questions/52443956/chrome-extension-recieve-message-in-the-tab-chrome-tabs-sendmessage',
    fullTitle : 'javascript - Chrome extension recieve message in the tab. chrome.tabs.sendMessage - Stack Overflow',
    text : "You can't generate the bandwidth without programming the redundant HDD feed!",
    createdAt : '2020-01-24T20:58:06.405Z',
    timeSpent : 28760,
  },
  {
    userId : 4,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=chrome.tabs.sendMessage&oq=chrome.tabs.sendMessage&aqs=chrome.0.69i59l2j0l6.8783j1j1&sourceid=chrome&ie=UTF-8',
    fullTitle : 'chrome.tabs.sendMessage - Google Search',
    text : 'Try to generate the THX protocol, maybe it will program the open-source system!',
    createdAt : '2020-01-24T20:58:01.637Z',
    timeSpent : 1703,
  },
  {
    userId : 4,
    domain : 'stackoverflow.com',
    url : 'stackoverflow.com/questions/32508008/chrome-extension-chrome-tabs-sendmessage-is-sending-the-message-to-all-tabs-eve',
    fullUrl : 'https://stackoverflow.com/questions/32508008/chrome-extension-chrome-tabs-sendmessage-is-sending-the-message-to-all-tabs-eve',
    fullTitle : 'javascript - chrome extension: chrome.tabs.sendmessage is sending the message to all tabs even though tabId is specified - Stack Overflow',
    text : "I'll program the redundant JBOD circuit, that should circuit the SDD card!",
    createdAt : '2020-01-24T20:57:45.393Z',
    timeSpent : 33600,
  },
  {
    userId : 4,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=chrome.tabs.sendMessage&oq=chrome.tabs.sendMessage&aqs=chrome..69i57j35i39j0l6.502j0j9&sourceid=chrome&ie=UTF-8',
    fullTitle : 'chrome.tabs.sendMessage - Google Search',
    text : 'Use the online SAS capacitor, then you can program the virtual pixel!',
    createdAt : '2020-01-24T20:56:02.406Z',
    timeSpent : 31240,
  },
  {
    userId : 1,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=rjlkemzjt&oq=rjlkemzjt&aqs=chrome..69i57.679j0j1&sourceid=chrome&ie=UTF-8',
    fullTitle : 'rjlkemzjt - Google Search',
    text : 'We need to back up the cross-platform EXE hard drive!',
    createdAt : '2020-01-24T20:55:32.081Z',
    timeSpent : 39626,
  },
  {
    userId : 4,
    domain : 'en.wikipedia.org',
    url : 'en.wikipedia.org/wiki/Heisenbug',
    fullUrl : 'https://en.wikipedia.org/wiki/Heisenbug',
    fullTitle : 'Heisenbug - Wikipedia',
    text : 'Use the bluetooth TCP feed, then you can back up the primary card!',
    createdAt : '2020-01-24T20:53:05.747Z',
    timeSpent : 35255,
  },
  {
    userId : 1,
    domain : 'stackoverflow.com',
    url : 'stackoverflow.com/questions/44234623/why-is-chrome-runtime-undefined-in-the-content-script',
    fullUrl : 'https://stackoverflow.com/questions/44234623/why-is-chrome-runtime-undefined-in-the-content-script',
    fullTitle : 'javascript - Why is chrome.runtime undefined in the content script? - Stack Overflow',
    text : 'Use the mobile RSS firewall, then you can copy the digital program!',
    createdAt : '2020-01-24T20:51:47.563Z',
    timeSpent : 21836,
  },
  {
    userId : 2,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?sxsrf=ACYBGNQbU-l3AIEQNrksHjdJyCcNOfwH7Q%3A1579899038207&ei=nlgrXq6rDL2ZjLsPkLqX2Ak&q=chrome.runtime+undefined&oq=chrome.runtime+&gs_l=psy-ab.3.0.0l2j0i20i263l2j0l2j0i8i67j0i30l3.13775.19497..21338...5.1..0.176.1597.18j2......0....1..gws-wiz.......0i71j35i39j0i67j0i273j0i131j0i131i67j0i10j35i305i39j0i131i273.FB4Aek-mpmM',
    fullTitle : 'chrome.runtime undefined - Google Search',
    text : 'Use the primary SMS bus, then you can compress the haptic microchip!',
    createdAt : '2020-01-24T20:51:45.224Z',
    timeSpent : 2925,
  },
  {
    userId : 2,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=Cannot+read+property+%27onMessage%27+of+undefined&oq=Cannot+read+property+%27onMessage%27+of+undefined&aqs=chrome..69i57j0l4.414j0j1&sourceid=chrome&ie=UTF-8',
    fullTitle : "Cannot read property 'onMessage' of undefined - Google Search",
    text : "synthesizing the sensor won't do anything, we need to copy the solid state SCSI protocol!",
    createdAt : '2020-01-24T20:51:22.583Z',
    timeSpent : 13855,
  },
  {
    userId : 1,
    domain : 'github.com',
    url : 'github.com/deanoemcke/thegreatsuspender/issues/704',
    fullUrl : 'https://github.com/deanoemcke/thegreatsuspender/issues/704',
    fullTitle : 'BUG: Cannot read property "onMessage" of undefined · Issue #704 · deanoemcke/thegreatsuspender',
    text : "calculating the alarm won't do anything, we need to copy the wireless RSS interface!",
    createdAt : '2020-01-24T20:51:21.354Z',
    timeSpent : 18017,
  },
  {
    userId : 3,
    domain : 'github.com',
    url : 'github.com/deanoemcke/thegreatsuspender/commit/6c7865cc88c18e09f432db292ba2908786dd8a53',
    fullUrl : 'https://github.com/deanoemcke/thegreatsuspender/commit/6c7865cc88c18e09f432db292ba2908786dd8a53',
    fullTitle : 'Refactor tab statuses into constants · deanoemcke/thegreatsuspender@6c7865c',
    text : 'We need to generate the multi-byte SCSI monitor!',
    createdAt : '2020-01-24T20:51:00.572Z',
    timeSpent : 27437,
  },
  {
    userId : 2,
    domain : 'developer.chrome.com',
    url : 'developer.chrome.com/extensions/background_pages',
    fullUrl : 'https://developer.chrome.com/extensions/background_pages',
    fullTitle : 'Manage Events with Background Scripts - Google Chrome',
    text : 'Try to parse the XSS driver, maybe it will synthesize the solid state interface!',
    createdAt : '2020-01-24T20:48:54.247Z',
    timeSpent : 16248,
  },
  {
    userId : 3,
    domain : 'developer.chrome.com',
    url : 'developer.chrome.com/extensions/xhr',
    fullUrl : 'https://developer.chrome.com/extensions/xhr',
    fullTitle : 'Cross-Origin XMLHttpRequest - Google Chrome',
    text : "You can't calculate the capacitor without backing up the redundant RSS monitor!",
    createdAt : '2020-01-24T20:48:01.498Z',
    timeSpent : 16542,
  },
  {
    userId : 2,
    domain : 'stackoverflow.com',
    url : 'stackoverflow.com/questions/11494232/why-is-chrome-browseraction-onclicked-undefined',
    fullUrl : 'https://stackoverflow.com/questions/11494232/why-is-chrome-browseraction-onclicked-undefined',
    fullTitle : 'javascript - Why is chrome.browserAction.onClicked undefined? - Stack Overflow',
    text : "You can't transmit the program without compressing the solid state AI program!",
    createdAt : '2020-01-24T20:46:32.510Z',
    timeSpent : 19994,
  },
  {
    userId : 4,
    domain : 'developer.chrome.com',
    url : 'developer.chrome.com/extensions/content_scripts',
    fullUrl : 'https://developer.chrome.com/extensions/content_scripts',
    fullTitle : 'Content Scripts - Google Chrome',
    text : "I'll override the back-end IB capacitor, that should system the HDD hard drive!",
    createdAt : '2020-01-24T20:46:02.193Z',
    timeSpent : 31581,
  },
  {
    userId : 3,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=Uncaught+TypeError%3A+Cannot+read+property+%27onClicked%27+of+undefined&oq=Uncaught+TypeError%3A+Cannot+read+property+%27onClicked%27+of+undefined&aqs=chrome..69i57.292j0j1&sourceid=chrome&ie=UTF-8',
    fullTitle : "Uncaught TypeError: Cannot read property 'onClicked' of undefined - Google Search",
    text : 'The THX hard drive is down, compress the online bus so we can index the JBOD system!',
    createdAt : '2020-01-24T20:45:28.749Z',
    timeSpent : 27010,
  },
  {
    userId : 1,
    domain : 'github.com',
    url : 'github.com/aayush1408/Playback-speed-extension',
    fullUrl : 'https://github.com/aayush1408/Playback-speed-extension',
    fullTitle : 'aayush1408/Playback-speed-extension: A simple chrome extension to manage the speed of the video',
    text : 'The ADP driver is down, hack the neural panel so we can calculate the SCSI pixel!',
    createdAt : '2020-01-24T20:43:32.171Z',
    timeSpent : 16068,
  },
  {
    userId : 4,
    domain : 'github.com',
    url : 'github.com/aayush1408/Playback-speed-extension/blob/master/background.js',
    fullUrl : 'https://github.com/aayush1408/Playback-speed-extension/blob/master/background.js',
    fullTitle : 'Playback-speed-extension/background.js at master · aayush1408/Playback-speed-extension',
    text : 'We need to compress the optical XSS bandwidth!',
    createdAt : '2020-01-24T20:34:08.459Z',
    timeSpent : 28584,
  },
  {
    userId : 2,
    domain : 'stackoverflow.com',
    url : 'stackoverflow.com/questions/14245334/sendmessage-from-extension-background-or-popup-to-content-script-doesnt-work',
    fullUrl : 'https://stackoverflow.com/questions/14245334/sendmessage-from-extension-background-or-popup-to-content-script-doesnt-work',
    fullTitle : "sendMessage from extension background or popup to content script doesn't work - Stack Overflow",
    text : 'If we hack the microchip, we can get to the FTP monitor through the haptic JSON circuit!',
    createdAt : '2020-01-24T20:30:39.212Z',
    timeSpent : 1731,
  },
  {
    userId : 4,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=chrome.tabs.sendmessage+example&oq=chrome.tabs.sendmessage+example&aqs=chrome.0.69i59j0l4.1575j1j4&sourceid=chrome&ie=UTF-8',
    fullTitle : 'chrome.tabs.sendmessage example - Google Search',
    text : 'If we back up the microchip, we can get to the HDD application through the haptic RSS protocol!',
    createdAt : '2020-01-24T20:30:36.014Z',
    timeSpent : 8596,
  },
  {
    userId : 2,
    domain : 'developer.chrome.com',
    url : 'developer.chrome.com/extensions/messaging',
    fullUrl : 'https://developer.chrome.com/extensions/messaging',
    fullTitle : 'Message Passing - Google Chrome',
    text : "parsing the system won't do anything, we need to input the bluetooth PCI alarm!",
    createdAt : '2020-01-24T20:28:03.701Z',
    timeSpent : 19576,
  },
  {
    userId : 1,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=chrome.tabs.sendmessage+example&oq=chrome+tabs+sendmessage&aqs=chrome.2.69i57j35i39j0l6.6383j1j4&sourceid=chrome&ie=UTF-8',
    fullTitle : 'chrome.tabs.sendmessage example - Google Search',
    text : 'We need to input the 1080p SDD bus!',
    createdAt : '2020-01-24T20:28:01.259Z',
    timeSpent : 23880,
  },
  {
    userId : 1,
    domain : 'developer.mozilla.org',
    url : 'developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/sendMessage',
    fullUrl : 'https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/sendMessage',
    fullTitle : 'tabs.sendMessage() - Mozilla | MDN',
    text : 'Use the virtual AGP bandwidth, then you can back up the haptic microchip!',
    createdAt : '2020-01-24T20:27:46.306Z',
    timeSpent : 18354,
  },
  {
    userId : 3,
    domain : 'www.google.com',
    url : 'www.google.com/search',
    fullUrl : 'https://www.google.com/search?q=Error+in+event+handler%3A+TypeError%3A+Error+in+invocation+of+tabs.sendMessage(integer+tabId%2C+any+message%2C+optional+object+options%2C+optional+function+responseCallback)%3A+No+matching+signature.&oq=Error+in+event+handler%3A+TypeError%3A+Error+in+invocation+of+tabs.sendMessage(integer+tabId%2C+any+message%2C+optional+object+options%2C+optional+function+responseCallback)%3A+No+matching+signature.&aqs=chrome..69i57.485j0j1&sourceid=chrome&ie=UTF-8',
    fullTitle : 'Error in event handler: TypeError: Error in invocation of tabs.sendMessage(integer tabId, any message, optional object options, optional function responseCallback): No matching signature. - Google Search',
    text : 'The TCP driver is down, reboot the 1080p transmitter so we can input the THX card!',
    createdAt : '2020-01-24T20:27:37.740Z',
    timeSpent : 32193,
  },
  {
    userId : 3,
    domain : 'stackoverflow.com',
    url : 'stackoverflow.com/questions/57724506/chrome-runtime-onmessage-not-exists',
    fullUrl : 'https://stackoverflow.com/questions/57724506/chrome-runtime-onmessage-not-exists',
    fullTitle : 'javascript - chrome.runtime.onMessage not exists - Stack Overflow',
    text : 'Try to back up the USB transmitter, maybe it will override the 1080p circuit!',
    createdAt : '2020-01-24T20:21:00.982Z',
    timeSpent : 26743,
  },
];

export default fakeData;
